# Generated by Django 3.2.3 on 2021-05-27 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinqLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'verbose_name': 'Linq Label',
                'verbose_name_plural': 'Linq Labels',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LinqUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.linqlabel')),
            ],
            options={
                'verbose_name': 'Linq Url',
                'verbose_name_plural': 'Linq Urls',
                'ordering': ['-timestamp'],
            },
        ),
    ]
