# Generated by Django 3.2.3 on 2022-11-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
