# Generated by Django 3.2.3 on 2022-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_added_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='linqlabel',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
