# Generated by Django 3.2.3 on 2022-12-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_linq_label_model_name_max_lenght'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linqurl',
            name='url',
            field=models.TextField(),
        ),
    ]
