# Generated by Django 3.2.3 on 2023-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_linq_url_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='linqurl',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
