# Generated by Django 3.2.3 on 2023-04-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('added', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SnippetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('added', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('new_item', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snippet Category',
                'verbose_name_plural': 'Snippet Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SnippetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('added', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='app.snippetcategory')),
                ('snippet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.snippet')),
            ],
            options={
                'verbose_name': 'Snippet Label',
                'verbose_name_plural': 'Snippet Labels',
                'ordering': ['-timestamp'],
            },
        ),
    ]
